host: "localhost"
url: "https://silviamaggiphotography.com"
baseurl: ""
posts_limit: 20

title: Silvia Maggi
tagline: 
description: 
permalink: /:categories/:title/
keywords:
  photography
timezone: Europe/Rome
logo: /assets/images/smp-og-image.jpg
author:
  name: Silvia Maggi
  email: hello@silviamaggidesign.com

main:
  smp_avatar_src: /assets/images/silviamaggi-avatar.png
  smp_tagline: 'Tagline here'
  smp_bio: 'Bio here'

exclude: 
  - README.md
include: ["_pages", "_redirects"]

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      is_post: true
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "page"

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:path/

# Taxonomy
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    tag: '/tag/:name/'
    category: '/category/:name/'
  slug_mode: latin
  date: 2021-08-15 13:45

excerpt_separator: <!--more-->

# Responsive images
# responsive_image:
#   template: _includes/pattern-responsive-image.html
#   sizes:
#     - width: 576
#       quality: 80
#     - width: 768
#       quality: 80
#     - width: 1200
#       quality: 90
#   strip: true
#   output_path_format: assets/images/responsive/%{width}/%{basename}

# Plugins
plugins:
  - jekyll-sitemap
  - jekyll-archives
  # - jekyll-responsive-image