# -------------------
# Site settings
# -------------------
host: 'localhost'
url: 'https://silviamaggiphotography.com'
baseurl: ''
lang: 'en-GB'
title: 'Silvia Maggi Photography'
tagline: '“She stayed behind to take a picture”'
timezone: Europe/London
logo: '/assets/images/smp-logo.svg'
brand: '/assets/images/smp-og-image.jpg'
smp_latestposts_limit: 3

# -------------------
# Personal data
# -------------------
author:
  name: 'Silvia Maggi'
  givenName: 'Silvia'
  familyName: 'Maggi'

# -------------------
# Profile
# -------------------
link:
  - name: Email
    label: hello@silviamaggidesign.com
    url: mailto:hello@silviamaggidesign.com
  - name: Personal Website
    label: Silvia Maggi Design
    url: https://silviamaggidesign.com
  - name: GitHub
    label: GitHub profile
    url: https://github.com/silviamaggi

# -------------------
# Inclusions
# -------------------
include: ["_pages"]

# -------------------
# SASS
# -------------------
sass:
  sass_dir: /assets/css/partials/
  sourcemap: development

# -------------------
# About
# -------------------
description: 'Silvia is an amateur photographer. Enjoy her pictures!'
keywords:
  photography

# -------------------
# Jekyll defaults
# -------------------
permalink: /:title/
defaults:
  - scope:
      path: ''
    values:
      layout: 'default'

# -------------------
# Jekyll plugins
# -------------------
plugins:
  - jekyll-archives

# -------------------
# Jekyll archives
# -------------------
jekyll-archives:
  enabled:
    - categories
    - tags
  layout: archive
  permalinks:
    category: '/albums/:name/'
    tag: '/tag/:name/'
  slug_mode: latin
  date: 2021-08-15 13:45

# -------------------
# Markdown
# -------------------
kramdown:
  syntax_highlighter_opts:
    disable: true